packages:
  - apps/*
  - packages/*

catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@cloudflare/workers-types": ^4.20251213.0
  better-auth: ^1.4.9
  alchemy: ^0.82.1
  next: ^16.1.1
  react: ^19.2.3
  react-dom: ^19.2.3
  drizzle-orm: ^0.45.1
  drizzle-kit: ^0.31.8
  tailwindcss: ^4.1.18
  "@tailwindcss/postcss": ^4.1.18
  lucide-react: ^0.562.0
  fumadocs-core: 16.4.7
  fumadocs-mdx: 14.2.6
  fumadocs-ui: 16.4.7
  "@t3-oss/env-core": ^0.13.1
  "@t3-oss/env-nextjs": ^0.13.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  tailwind-merge: ^3.4.0
  "@radix-ui/react-switch": ^1.1.4
  "@radix-ui/react-tabs": ^1.1.4
  "@radix-ui/react-dropdown-menu": ^2.1.15
  "@radix-ui/react-checkbox": ^1.1.5
  "@radix-ui/react-label": ^2.1.4
  "@radix-ui/react-slot": ^1.2.3
  xlsx: ^0.18.5
  csv-parse: ^5.6.0
  csv-stringify: ^6.5.2
  xml-js: ^1.6.11
  tsx: ^4.19.4
  postcss: ^8.5.6
