packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@cloudflare/workers-types": ^4.20251213.0
  "@libsql/client": 0.15.15
  libsql: 0.5.22
  better-auth: ^1.4.9
  alchemy: ^0.82.1
